jobs:
  include:
    - stage: release
      language: node_js
      node_js: '10'
      services:
        - docker
      script:
        - docker build -t cadamsio/interview-api .
        - yarn install
        - yarn semantic-release
      after_success:
        - yarn travis-deploy-once "npm run semantic-release"

stages:
  - test
  - name: release
    if: branch = master AND type = push AND fork = false

branches:
  except:
    - /^v\d+\.\d+\.\d+$/