jobs:
  include:
    - stage: release
      language: node_js
      node_js: '8.10.0'
      services:
        - docker
      script:
        - docker build -t chaseadams/interview-api .
        - yarn semantic-release
        - yarn build && yarn deploy

stages:
  - test
  - name: release
    if: branch = master AND type = push AND fork = false

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
