service: interview-api

plugins:
  - serverless-plugin-typescript
  - serverless-express
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-1
  memorySize: 128

functions:
  app:
    handler: handler.handler
    environment:
      SERVERLESS: "true"
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
